name: Deploy to AWS with Terraform

on:
  push:
    branches:
      - main  # O pipeline será acionado quando houver um push na branch main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar AWS CLI
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      # 3. Instalar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'  # Especifique a versão do Terraform

      # 4. Inicializar o Terraform
      - name: Terraform Init
        run: terraform init

      # 5. Validar os arquivos Terraform
      - name: Terraform Validate
        run: terraform validate

      # 6. Aplicar a infraestrutura com Terraform
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
          echo "terraform_apply_status=Success" >> $GITHUB_ENV  # Usando Environment Files para salvar status

      # 7. Exibir o status da aplicação (opcional)
      - name: Show Terraform Outputs
        run: echo "Terraform apply completed: ${{ env.terraform_apply_status }}"

      
  # deploy:
  #   runs-on: ubuntu-latest  # Utilizando o Ubuntu para rodar o pipeline

  #   steps:
  #     # 1. Checkout do código
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     # 2. Configuração do AWS CLI
  #     - name: Set up AWS CLI
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1  # Altere para a sua região da AWS

  #     # 3. Enviar os arquivos para o S3
  #     - name: Deploy to S3
  #       run: |
  #         aws s3 sync . s3://sandbox-pucrs/ --exclude ".git/*" --delete --exact-timestamps
  #       # 'sandbox-pucrs' é o nome do seu bucket no S3
  #       # --delete remove arquivos antigos no S3 que não existem mais no repositório
